# a_tensor_initialization.py

In [96]:
import torch

# 기본 데이터 타입 float32
t1 = torch.Tensor([1,2,3], device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

t2 = torch.tensor([1,2,3], device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

a1 = torch.tensor(1)
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])
print(a4.shape, a4.ndim)

a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]],
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

# 내부 리스트들의 길이가 다르면 에러가 발생함
a11 = torch.tensor([
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

### 기술적 사항 / 고찰 내용
위 코드 블럭은 torch.Tensor와 torch.tensor의 차이점을 시각적으로 보여주고 만들어진 tensor의 shape와 ndim을 계속 보여줌으로 tensor에 대한 이해를 도와주고 있다고 생각합니다.
마지막 부분의 에러가 나는 부분을 보면 한쪽은 [1, 2, 3], 다른 한쪽은 [4, 5] 형태로 길이가 서로 다름을 알 수 있습니다. 그렇기에 shape 불일치 오류가 발생하며 다차원 텐서를 생성할 때, 내부 리스트들의 크기가 일치해야함을 시각적으로 알 수 있었습니다.


# b_tensor_initialization_copy.py

In [97]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)  # 데이터를 복사해 새로운 텐서 생성

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)  # 복사본은 영향을 안받음
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch. Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100  # 원본 numpy 배열을 변경하면 텐서도 함께 변경

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


### 기술적 사항 / 고찰 내용
이 코드 블록은 텐서 생성 함수들이 원본 데이터의 값을 복사하는지, 아니면 메모리 주소를 공유하는지를 비교하여 보여주고 있습니다. 특히 NumPy 배열을 torch.as_tensor로 변환한 경우, 원본 배열의 값을 변경하자 텐서의 값도 함께 바뀌는 것을 확인할 수 있었습니다.

# c_tensor_initialization_constant_values.py

In [98]:
import torch

t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1)  # 입력과 동일한 shape, dtype을 갖는 텐서 생성
print(t1)
print(t1_like)

t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

t4 = torch.eye(n=3)
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([  1.0000,   1.8750,  27.0000, 256.0000])
tensor([0.0000, 2.1250, 3.0000, 5.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### 기술적 사항 / 고찰 내용
해당 코드는 ones, zeros, empty, eye와 같이 특정 상수 값으로 채워진 텐서를 생성하는 방법을 보여줍니다. _like 함수를 사용하면 기존 텐서의 shape이나 dtype 같은 속성을 그대로 가져와 새로운 텐서를 만들 수 있어 편리하다는 것을 알 수 있었습니다. 또한 empty는 텐서를 초기화하지 않고 메모리 공간만 할당하기 때문에, 예측할 수 없는 값이 들어있다는 점을 눈으로 직접 확인할 수 있었습니다.

# d_tensor_initialization_random_values.py

In [99]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

# 평균 0, 표준편차 1의 표준 정규 분포에서 값을 샘플링
t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

# 난수 생성 시드를 고정
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729) # 위와 값은 값으로 고정했기에 같은 텐서 생성됨
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[13, 14]])
tensor([[0.2985, 0.2210, 0.1837]])
tensor([[-2.1456,  0.3064, -0.4560]])
tensor([[12.1297,  9.4018],
        [10.4189,  9.1229],
        [ 9.7090,  9.6984]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### 기술적 사항 / 고찰 내용
이 코드 블록은 다양한 종류의 무작위 텐서를 생성하는 방법을 다루고 있습니다. randint, rand, randn 등 각 함수가 어떤 확률 분포를 따르는지 보여주고 있습니다.
torch.manual_seed는 시드 값을 고정하면 난수 생성이 동일하게 반복되는 것을 random1과 random3의 비교를 통해서 확인할 수 있었습니다.

# e_tensor_type_conversion.py

In [100]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


### 기술적 사항 / 고찰 내용
위 코드는 텐서를 생성할 때 데이터 타입을 지정하거나, 이미 생성된 텐서의 타입을 변환하는  다양한 방법을 보여주고 있습니다. 여러 메소드가 있지만 적절히 사용하면 전부 원하는 데이터 타입으로 변경할 수 있음을 깨달았습니다. 마지막에 서로 다른 타입의 텐서들을 연산했을 때, 자동으로 torch.float64로 결과가 나오는 것을 보고 Pytorch의 타입 처리 방식에 대해서 더 이해할 수 있었던 것 같습니다.

# f_tensor_operations.py

In [101]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### 기술적 사항 / 고찰 내용
위 코드는 텐서의 기본적인 사칙연산을 보여주고 있습니다. torch.add와 같은 함수를 사용하는 방법과 + 같은 연산자를 사용하는 방법, 두 가지 모두 동일한 결과를 보여준다는 것을 시각적으로 알 수 있었습니다.

# g_tensor_operations_mm.py

In [102]:
import torch

# 내적 계산
t1 = torch.dot(
    torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # 2차원 텐서간의 행렬 곱셈 계산
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # 3차원 배치 행렬 곱셈
print(t7.size())

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


### 기술적 사항 / 고찰 내용
이 코드는 다양한 행렬 곱셈 연산의 차이점을 보여주고 있습니다. 각각의 연산들을 직접 사용 해보고 값을 확인 해보며 이해에 더 도움이 되었습니다.

# h_tensor_operations_matmul.py

In [103]:
import torch

t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size()) # 1D, 1D 이기에 내적

t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())

t7 = torch.rand(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size()) # 3D, 3D 이기에 배치 행렬 곱셈

t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


### 기술적 사항 / 고찰 내용
이 코드 블록은 torch.matmul이라는 함수가 텐서의 shape에 따라 어떻게 동작하는지 보여주고 있습니다. 입력에 따라서 알아서 g 파트에 있던 dot, mm, bmm을 사용하고 있기에 매우 편리한 기능이라고 생각했습니다.

# i_tensor_broadcasting.py

In [104]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) # shape가 서로 달라서 작은 쪽이 확장됨

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) # 이 경우 t4가 더 작아서 [[4, 5], [4, 5], [4, 5]]로 확장됨

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())

t27 = torch.ones(4) * 5
print(t27)

t28 = torch.pow(t27, 2)
print(t28)

exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)

tensor([2., 4., 6.])
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
torch.Size([3, 28, 28])
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


### 기술적 사항 / 고찰 내용
위 코드는 shape가 서로 다른 텐서끼리 연산을 다양한 예시를 통해서 설명해주고 있습니다. 크기가 작은 텐서가 크기가 큰 텐서의 shape에 맞춰 확장되어 연산되는 과정을 다양한 shape 조합들로 보여주어 원리를 쉽게 이해할 수 있었습니다.

# j_tensor_indexing_slicing.py

In [105]:
import torch

x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

print(x[1])
print(x[:, 1])  # ':'는 해당 차원의 모든 요소를 의미
print(x[1, 2])
print(x[:, -1])

print(x[1:])
print(x[1:, 3:]) # 이 경우는 1번 행부터 끝까지, 3번 열부터 끝까지

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

z = torch.tensor(
    [[1, 2, 3, 4],
     [2, 3, 4, 5],
     [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

# 슬라이싱으로 선택된 영역에 값을 할당하면 원본 텐서가 변경됨
z[1:, 1:3] = 0
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


### 기술적 사항 / 고찰 내용
이 코드 블록은 텐서의 특정 원소나 부분에 접근하는 인덱싱과 슬라이싱 기법을 보여주고 있습니다. 행, 열, 특정 구간을 자유롭게 잘라내고, 심지어 해당 부분의 값을 한 번에 변경할 수 있다는 것을 y[1:4, 2] = 1 같은 코드를 통해 확인할 수 있었습니다. 텐서 데이터를 다룰 때 원하는 부분을 효과적으로 제어하는 필수적인 방법임을 알게 되었습니다.

# k_tensor_reshaping.py

In [106]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2) # view()는 원소 개수를 유지하며 shape 변경
t3 = t1.reshape(1, 6) # reshape()은 view()와 유사하지만, 메모리가 비연속적이여도 가능함
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)
t5 = torch.arange(6).view(2, 3)
print(t4)
print(t5)

t6 = torch.tensor([[[1], [2], [3]]])
# squeeze()는 크기가 1인 차원을 제거하여 차원을 축소함
t7 = t6.squeeze()


t8 = t6.squeeze()
print(t7)
print(t8)

t9 = torch.tensor([1, 2, 3])
# unsqueeze()는 지정된 dim에 크기가 1인 차원을 추가함
t10 = t9.unsqueeze(1)
print(t10)

t11 = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]]
)
t12 = t11.unsqueeze(1)
print(t12, t12.shape)

t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t14 = t13.flatten()

print(t14)

t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size())
# permute()는 괄호 안의 순서대로 차원을 재배치함

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(1, 0))
print(t20)
print(t21)

t22 = torch.transpose(t19, 0, 1)
print(t22)

t23 = torch.t(t19)
print(t23)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 기술적 사항 / 고찰 내용
이 코드는 텐서의 전체 원소 수는 유지하면서 shape을 바꾸는 다양한 방법을 보여주고 있습니다. view와 reshape의 기본적인 기능부터, 크기가 1인 차원을 제거하는 squeeze, 추가하는 unsqueeze 방법을 시각적인 결과로 볼 수 있어서 이해하기 좋았습니다. 그리고 permute의 경우 차원의 순서를 원하는 대로 재배치 할 수 있기에 이미지나 여러 부분에서 유용하겠다고 생각했습니다.

# l_tensor_concat.py

In [107]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

# torch.cat()은 기존의 dim을 따라 여러 텐서를 이어 붙여줌
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

t5 = torch.arange(0, 3)
t6 = torch.arange(3, 8)

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)
print(t7)

t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)

t10 = torch.cat((t8, t9), dim=0)
print(t10.size())
print(t10)

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())
print(t11)

t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())
print(t16)

t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())
print(t19)

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())
print(t20)

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())
print(t21)

torch.Size([2, 6, 3])
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


### 기술적 사항 / 고찰 내용
이 코드 블록은 torch.cat 함수를 사용하여 여러 텐서를 특정 차원을 기준으로 이어 붙이는 것을 보여주고 있습니다. dim의 값에 따라서 어떻게 달라지는지 출력 값을 통해서 확인할 수 있었습니다.

# m_tensor_stacking.py

In [108]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# torch.stack()은 새로운 dim을 만들어 텐서들을 쌓음
# 입력 텐서들의 shape이 모두 동일해야 함
t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))
# stack(dim=0)은 각 텐서에 unsqueeze(dim=0)을 적용한 뒤 cat(cat=0)하는 것과 동일함

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)

print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


### 기술적 사항 / 고찰 내용
이 코드는 torch.stack이 torch.cat에 대해서 비교하며 자세히 보여주고 있습니다. 과정과 결과를 보면 stack은 새로운 차원을 만들어 그곳에 텐서를 쌓고 cat은 기존 차원을 따라서 합친다는 것을 알 수 있었습니다. 마지막으로, unsqueeze 연산을 잘 활용하면 torch.cat을 통홰 torch.stack과 동일한 결과를 얻을 수 있음 또한 알 수 있었습니다.

# n_tensor_vstack_hstack.py

In [109]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))  # vstack은 수직으로 쌓음
print(t3)

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

t7 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])
print(t9.shape)

print(t9)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11)) # hstack은 수평으로 쌓음
print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

t16 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


### 기술적 사항 / 고찰 내용
마지막 코드 블록은 텐서를 수직또는 수평으로 쌓는 방법을 직관적으로 보여주고 있습니다. 특히 cat 함수에서 dim을 지정하는 대신, vstack이나 hstack을 사용해서 코드가 더 직관적으로 보인다고 생각했습니다. 마지막으로, 결과 출력을 통해서 실제로 어떻게 되었는지 볼 수 있어서 메소드의 이해에 도움이 되었습니다.

# 숙제후기
이번 과제를 통해서 tensor가 무엇이고 tensor를 이용하는 다양한 방법들에 대해서 실습해 볼 수 있었습니다. 양이 많았던 만큼 전부 기억에는 힘들어도 이번 과제가 경험이 되어서 사용함에 있어서는 문제 없을 것이라고 생각이 들었습니다.
처음에는 많은 양에 힘들었지만,딥러닝에 관해서 스스로 공부를 더 해볼 수 있게 만들어주는 과제였다고 생각합니다.